server:
  port: 9530
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: v2sual
          uri: ws:lb://v2sual
          predicates:
            - Path=/service/v2sual/**
          filters:
            - StripPrefix=2
        - id: webide
          uri: lb://webide
          predicates:
            - Path=**
      loadbalancer:
        use404: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9528/eureka
    register-with-eureka: false