server:
  port: 9530

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        # client request -> webide service
        - id: webide
            uri: lb://webide
            predicates:
              - Path=/**
        # client request -> v2sual service(websocket)
        - id: v2sual-websocket
          uri: dlb:ws://serviceId
          predicates:
            - Path=/service/{productType}/{productId}/socket.io/**
          filters:
            - StripPrefix=3
        # client request -> v2sual service(http)
        - id: v2sual-http
          uri: dlb://serviceId
          predicates:
            - Path=/service/{productType}/{productId}/**
          filters:
            - StripPrefix=3
      loadbalancer:
        use404: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9528/eureka
    register-with-eureka: false

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            web: trace
        cloud:
          gateway: trace
        http:
          server:
            reactive: trace
        web:
          reactive: trace
    redisratelimiter: trace
    reactor:
      netty: trace